/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package producer

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
        assertEquals(2, 2, "2 should equal 2");
    }
}
