version: '3'

services:
  delivery_api:
    build:
      context: .
      dockerfile: ./Dockerfile-delivery_api
    environment:
      - BROKERS=kafka:9092
    depends_on:
      - kafka
      - zookeeper

  delivery_handler:
    build:
      context: .
      dockerfile: ./Dockerfile-delivery_handler
    environment:
      - BROKERS=kafka:9092
    depends_on:
      - kafka
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3-debian-10
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2-debian-10
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9100:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
      - kafka
