FROM gradle:jdk17 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src

RUN gradle build --no-daemon

FROM openjdk:17

RUN mkdir /app

COPY --from=build /home/gradle/src/delivery_state/build/libs/ /app/

ENTRYPOINT ["java","-jar","/app/delivery_state.jar"]