FROM gradle:jdk17 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src

RUN gradle test --no-daemon
RUN gradle build --no-daemon

FROM openjdk:17

RUN mkdir /app

COPY --from=build /home/gradle/src/pickup_producer/build/libs/ /app/

ENTRYPOINT ["java","-jar","/app/pickup_producer.jar"]