FROM gradle:jdk17 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src

RUN gradle test --no-daemon
RUN gradle build --no-daemon

FROM openjdk:17

RUN mkdir /app

COPY --from=build /home/gradle/src/delivery_api/build/libs/ /app/

EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/delivery_api.jar"]