version: '3'

services:
  delivery_api:
    build:
      context: .
      dockerfile: ./Dockerfile-delivery_api
    ports:
      - 8080:8080
    environment:
      - BROKERS=kafka:9092
      - PORT=8080
      - CONNECTION_STRING=mongodb://lab:SuperSecret123@mongodb:27017
    depends_on:
      - kafka
      - zookeeper

  delivery_handler:
    build:
      context: .
      dockerfile: ./Dockerfile-delivery_handler
    environment:
      - BROKERS=kafka:9092
    depends_on:
      - kafka
      - zookeeper

  grafana:
    image: grafana/grafana:7.3.4
    container_name: grafana
    volumes:
      - ./.grafana:/var/lib/grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.23.0
    container_name: prometheus
    volumes:
      - ./.prometheus/etc:/etc/prometheus
      - ./.prometheus/data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  zookeeper:
    image: bitnami/zookeeper:3-debian-10
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2-debian-10
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9100:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
      - kafka

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lab
      - MONGO_INITDB_ROOT_PASSWORD=SuperSecret123
